name: Feature request
description: Propose a new feature
labels: ["type:feature"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What user outcome are we trying to achieve?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Proposed scope
      description: What is in/out of scope?
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How will we know it's done?
    validations:
      required: true
